FROM python:3.8-slim-buster

RUN mkdir -p /folder
WORKDIR /folder

RUN pip install --upgrade pip

COPY requirements_docker.txt ./
RUN pip install -r requirements_docker.txt

RUN pip install numpy \ pandas \ scikit-learn \ tensorflow \ seaborn \ plotly \ jupyter \ notebook

EXPOSE 8888

ENTRYPOINT [ "jupyter", "notebook", "--ip=0.0.0.0", "--allow-root", "--no-browser" ]




